### ISSUE TITLE
VQ in connector questions

### ISSUE THREAD

**Issue by sdorresteijn88** [i2group/analyze-connect-node-sdk#11]
Good afternoon,

I extended a existing connector with the VQ option. It's a very nice feature! I have 2 questions: one about Typescript and one about the deployment.

1. The color filtering is working perfectly but I still have a TypeScript error and I don't know how to solve it. Can you share any suggestions, or is this something you can add to the type 'VisualQueryCondition'?

I tried to extend the 'VisualQueryCondition' type, but without success. 

Below the error message.
![image](https://github.com/i2group/analyze-connect-node-sdk/assets/52672945/10513c1b-2c19-4034-b06a-515ce4d5525e)

Finally I changed the i2connect.d.ts and added the values to the VQConditions
```
export type VisualQueryCondition = {
        aspect?: VisualQueryConditionAspect;
        /**
         * The identifier of the property or metadata type to use in this query condition.
         */
        id: string;
        operator: VisualQueryConditionOperator;
        valueType: VisualQueryConditionValueType;
        values: Array<string>;
    };
```

2. I deployed the version of the VQ connector with 'npm run build' and 'npm pack'. I added this new version to my containerized configuration and deployed it again. The connector appears but all the entities are gone. Maybe some mismatch in the scheme. But the weird thing is that it worked perfect as an external connector.

This is the type 'i2connect-server', it's empty.
![image](https://github.com/i2group/analyze-connect-node-sdk/assets/52672945/ee123f0b-d6e5-416f-91b2-3f3031164743)

This is the type external (my dev environement), and this is working perfect.
![image](https://github.com/i2group/analyze-connect-node-sdk/assets/52672945/edb36425-2865-4cdf-a366-413d62a3924a)

**Comment by Anthony-Johnson-i2** [comment]
Hi @sdorresteijn88  (Steven)

Are you mapping your entity types to another schema in the instance where your palette is empty? 

We had an issue found with another customer recently where their i2 Connect VQ worked fine stand alone but when they added their connector to a deploy with an Information store  and then wanted to map  their types, any types that were included in that mapping  were incorrectly then not being seen as available for the VQ palette.

Here is the defect report for that:

https://support.i2group.com/s/article/2864

Cheers

**Comment by sdorresteijn88** [comment]
Morning @Anthony-Johnson-i2,

That's exactly what goes wrong for me. I deleted one mapping and than the entity is visible in VQ. For the stand alone (development version) I didn't add the mapping. 

I use the same scheme for all the i2 components to make the mapping more easily. So I don't think there is a work around to fix this issue. Will this be fixed soon?
