### ISSUE TITLE
Read value of VQ condition

### ISSUE THREAD

**Issue by sdorresteijn88** [i2group/analyze-connect-node-sdk#13]
Good morning,

What's the best approach to read the value with is added to the VQ condition? The solutions works but gives an error.

I created a VQ to filter persons where the surname contains some characters (e.g. 'Gen'). The value is stored in the .values but I can't resolve the Typescript errors.

```
const person = visualQuery.find( c => c.itemTypeIds != undefined && c.itemTypeIds[0] === 'ET5');

if (person != undefined){
  const personProps = person.conditions?.find(c => c.id === 'PER6');
  if (personProps.id === 'PER6' && personProps.operator === 'CONTAINS' && personProps.valueType === 'STRING'){
      const surNameContains = personProps.values[0];
    }
}
```
![image](https://github.com/i2group/analyze-connect-node-sdk/assets/52672945/51d6216d-8d97-492b-afc2-be0ba5d3b1fd)

I 'fixed' it by replacing the personProps for the code below.
```
const personProps = (person.conditions?.find(c => c.id === 'PER6')) as {
        id: string;
        operator: string;
        valueType: string;
        values?: string[];
      };
```

**Comment by Anthony-Johnson-i2** [comment]
@Jonny-Cornwell-i2  Is there a neater way of doing this  or is Steven's 'Fix' the way to go?
