### ISSUE TITLE
Adding the same entity to a graph multiple times

### ISSUE THREAD

**Issue by bohdanszymanik** [i2group/analyze-connect-node-sdk#16]
I've realised I'm getting different behaviour for the same connector when using the i2 web client versus i2 Premium ANB. In the web client when I add eg 'Fred Flintstone the 2nd' to the chart - I get one instance and no matter how many times I repeat the 'Copy to Chart' action it remains just one.
![image](https://github.com/i2group/analyze-connect-node-sdk/assets/271575/e8ed1679-c3d4-4362-a22a-e6c7a45ec266)

![image](https://github.com/i2group/analyze-connect-node-sdk/assets/271575/faa3ce2d-a112-40e0-868c-7241513fb7e2)

While with i2 Premium ANB - if I add again and again... I get multiple Fred Flintstone the 2nds.
![image](https://github.com/i2group/analyze-connect-node-sdk/assets/271575/aa3c7c3f-8cb0-4bf2-822a-fb3a8f9865f5)

Where the service is:
```
addService({
  id: 'addfred',
  name: 'For testing',
  resultItemTypes: [Person],
},
  ({result}) => {
    const protofred = result.addEntity(Person, 'abcdef')
    protofred.setProperty('First Name', 'Fred')
    protofred.setProperty('Last Name', 'Flintstone the 2nd')
  }
)
```
and Person comes from the definition in the example-connector in this repo.

Any hints on why this might be occurring?

**Comment by bohdanszymanik** [comment]
One thing I notice is that the identifier changes when the entity goes on the chart, but this behaviour is common to both i2 Premium ANB and to the i2 web client:
![image](https://github.com/i2group/analyze-connect-node-sdk/assets/271575/01778476-18af-48bb-9d1a-f7514ab554f2)

**Comment by Anthony-Johnson-i2** [comment]
I Just had a look at the new Nov.2023 release notes for Analysis Studio and Analysis Hub  and one of the highlights for the new release is that  i2 Notebook web-client now has support for System matching rules so will now behave more like ANBP in this respect.

[System matching rules suport](https://docs.i2group.com/release-material/as/2023.11/i2-as-2023.11.html#support-for-system-matching-rules)
