### ISSUE TITLE
Upgrading 4.4.0 to 4.4.1 for Semantic Seeded Searches

### ISSUE THREAD

**Issue by CharlesMarriott-VA** [i2group/analyze-connect-node-sdk#17]
We're running i2 Analyze FP1 and we've had issues with the the fallowing error message:

‪Failed to parse configuration information for the connector with identifier 'XXX' from the URL 'http://localhost:3011/config'. The connector with identifier 'XXX' specified SPI version 1.2, which is not supported by this server. This server supports the following SPI versions: 1.0–1.1.‬

The fix package.json -> dependencies "@i2analyze/i2connect": "^2.3.0", to version 2.1.6. However we now need to implement semanticseeds and need to use 2.3.0?

However, we get the above SPI error. 

Please let us know how to resolve this issue and perform SemanticSeeded searches.

**Comment by Jonny-Cornwell-i2** [comment]
Hi @CharlesMarriott-VA,

Using the [compatibility table](https://i2group.github.io/analyze-connect-node-sdk/#compatibility) I can see that you can use `@i2analyze/i2connect@2.2.0`. This should provide support for semantic searches, the version can be set explicitly in `package.json` file along with removing the `^` [(Caret) symbol](https://docs.npmjs.com/cli/v6/using-npm/semver#caret-ranges-123-025-004), see also:

```diff
-      "@i2analyze/i2connect": "^2.3.0"
+      "@i2analyze/i2connect": "2.2.0"
```

Cheers,
Jonny

**Comment by CharlesMarriott-VA** [comment]
Hello Johnny,

 

It now works. Thank you for that.

 

I guess I am confused that we I run the init, it gave me 2.3.0 instead of 2.2.0.

 

Is this a possible issue with the init?

 

 

Regards,

 

Charles Marriott

Senior Software Trainer

VA-Worldwide

 

AU P:+61 0419 792 502

E: ***@***.*** ***@***.***> 

 



 

 

This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. 

If you have received this email in error please notify IT Support on +61 2 6230 4999. 

Please note that any views or opinions presented in this email are solely those of the author and do not necessarily represent those of the company. 

Finally, the recipient should check this email and any attachments for the presence of viruses. The company accepts no liability for any damage caused by any virus transmitted by this email.

**Comment by Anthony-Johnson-i2** [comment]
Hi @Jonny-Cornwell-i2  Is there anything more you wish to add here before I close this out?

**Comment by Jonny-Cornwell-i2** [comment]
I don't think so, as things stand we expect the latest version installed by default and should someone wish to use an older version it will need to be downgraded via this process. If it becomes a more regular occurrence we can revisit and consider adding something to the cli for creating connectors.
