### ISSUE TITLE
Understanding the different schemas for i2 Analyze and i2 Connect and how they interact.

### ISSUE THREAD

**Issue by nondeterminickstic** [i2group/analyze-connect-node-sdk#18]
Hi there,
I've been directed here by the i2 Support helpdesk.

I'm wondering if I can get get some clarification on how the i2 Connect connector schema(s) are meant to interact with the i2 Analyze InfoStore/ChartStore schemas so data pulled-in via connectors can be stored in the ChartStore?

I have a couple of scenarios I'd like to discuss with regards to this..

1 -  A deployment of i2Analyze with the ChartStore and a single i2Connect connector.
Q: Is there any issue with using a copy of the connector's schema as the ChartStore schema and are there any instances where you shouldn't do this?

2 - A deployment of i2Analyze with the ChartStore and more than one i2Connect connector.
Q: I'm assuming a ChartStore schema is required which incorporates the elements (entities/fields/links) of both connectors? If so, what is the process for doing the mapping between i2C and ChartStore schemas?

Also..
- When would you use a gateway schema? Would this be in scenario #2? If so, how do you map the connector schemas to the gateway schema (I'm guessing that's what a gateway schema is there for)?

Cheers!

**Comment by Anthony-Johnson-i2** [comment]
Hi @nondeterminickstic 

As you have discovered, there are multiple possible ways that you can set things up.

Hopefully the latest documentation I am linking to below will tell you what you need to know.

[i2 Analyze Schemas](https://docs.i2group.com/analyze/i2_analyze_schemas.html)
[Item type conversion](https://docs.i2group.com/analyze/converting_records_between_types.html)

Over the last few releases a lot of work has gone in to the area of mapping and aligning schemas and if you are planing on using Visual Query with your  connector/connectors it would be good for you to be on our latest release as we had a side effect that mapping types between schemas as you might end up deciding to do was making them disappear from the visual query palette.

One thing which may not be immediately obvious but that  can be very useful is that the Gateway can have more than one Gateway schema and you can define that some of your connectors use/share one gateway schema and others use/share a different one. 

Whether you define schemas directly/separately  in your connectors or your connectors  use  Gateway schemas or even combinations of both will largely come down to how you want to manage things. 

The Item type conversion documentation I link to above is great for getting in to the nuts and bolts of this.

If you have an Information Store  and  a single Connector  and your connector can return all types/properties that you have defined for the information store that then the Information Store and Connector or Gateway  schema could be exactly the same.  Having these as discrete schemas however, and mapping your item types between them, will make your deployment more robust to change.

What is often found, is that a specific connector would return a subset of what you have defined in your information Store Schema  and if you used the same (larger)  information Store Schema for both it would not be a s good an experience for the user as if you had a specific schema in the gateway or your connector itself that just gave only the subset of entities links and properties that the connector would provide.

Once deployed and populated with data the information store schema is restricted as to what changes you can make without having to clear it down and start again with adding/ uploading your data so it is worth bearing this section of our documentation in mind:

[Configuring i2 Analyze schemas](https://docs.i2group.com/analyze/t_changing_schema.html)


Cheers

**Comment by nondeterminickstic** [comment]
Hi Anthony,

Thanks for the info. 
Just an add-on to this question, if I have a deployment of the chart store with the i2 Connect gateway and I want to lock down certain fields of entity/link data coming in from one or more connectors, can I still do this via implementing Item Type security (given there is no Info Store)? 
I'm assuming to do this I would need a gateway schema so the item types can be mapped from the connector schema(s), and then item type security is applied at this point by i2 Analyze?

Cheers!

**Comment by Ricardo-Antunes-i2** [comment]
Hi @nondeterminickstic,

Item type security only deals with access at an item type level (entity/link) not a property level. So you can prevent a group of users from having access to a specific link or entity, but you can not control this at the property level. See: [Item type security](https://docs.i2group.com/analyze/4.4.3/item-type-security.html for more information) for more information. If you have support entitlement, and if you would like property type security to be supported in the product then please raise a support [request](https://i2group.com/support-request) referencing this issue and it can be raised as a Request for Enhancement (RFE).

If you would like to restrict access to an item type on a connector you can refrence them connector item type directly by filling in the connector shortname along side the item type (see the item type security link I have attached to this message). If the item type you want to restrict is an aligned type referenced in the gateway schema then refrence the gateway shortame and the item type. Doing the latter restricts access to all connector item types aligned to the gateway item type you've restricted.

Hope this helps.

**Comment by Anthony-Johnson-i2** [comment]
Hi @nondeterminickstic 

I am just checking if you are OK for this issue to be closed given the information that @Ricardo-Antunes-i2 gave you a couple of weeks ago?

Cheers
