### ISSUE TITLE
Hide input based on other input

### ISSUE THREAD

**Issue by sdorresteijn88** [i2group/analyze-connect-node-sdk#20]
Good morning,

How can I hide a input when another input is true/false?

I will disable serverURL when the useLocalInstance is true.

```
form: {
      useLocalInstance: {
        label: 'Use local instance',
        logicalType: 'boolean',
        defaultValue: neo4jConfig.localInstance,
        isMandatory: true
      },
      serverURL: {
        label: 'Server URL (e.g. neo4j+s://fb84ade4.databases.neo4j.io)',
        logicalType: 'singleLineString',
        defaultValue: neo4jConfig.serverURL,
        isMandatory: false,
        hide: (requestInformation: services.IRequestInformation) => this.useLocalInstance,
      },
```

**Comment by Anthony-Johnson-i2** [comment]
Hi @sdorresteijn88  
I had a chat to development and unfortunately we do not currently have support for dynamic forms which alter like this dependent on input values.

As an alternative with both fields remaining visible, you could throw a "DetailedError" with a title set to present an error message to inform the user of an incorrect combination. 


Cheers

**Comment by sdorresteijn88** [comment]
@Anthony-Johnson-i2 thanks for your quick reply. Please can you raise a RFE? It would be a very useful feature.
