### ISSUE TITLE
DB Credential Encryption within the .env file.

### ISSUE THREAD

**Issue by nondeterminickstic** [i2group/analyze-connect-node-sdk#21]
Hi,
I'm utilising a .env file for holding the DB connection credentials of the connectors I'm developing. To add another level of security, I'm hoping to confirm whether there is a way to encrypt the DB login credentials within the .env file itself, similar to how the user credentials in the i2 Analyze user.registry file are encrypted?

If not, could you please advise what i2 recommend as best practice for ensuring the DB credentials are kept secure in the .env file? 

Cheers!

**Comment by Jonny-Cornwell-i2** [comment]
Hi,

As part of SDK there is no built in mechanism for encrypting/decrypting environment variables. Should you want to use encrypted values you'd also need to add code to decrypt those variables when accessing them in your connector.

Whilst developing, the best practice for a .env file is that it should be local to you and never checked in to source control or distributed, we have a [short summary here in the documentation](https://i2group.github.io/analyze-connect-node-sdk/guide/making-a-connector-configurable.html#handling-sensitive-information).

**Comment by nondeterminickstic** [comment]
Hi Jonny,
Thanks for the info. So I'm guessing you are referring to something like what is described in the below stackoverflow article?
https://stackoverflow.com/questions/65564126/encrypt-passwords-stored-in-environment-variables

If so, wouldn't that just move the secret that is being used for the encryption (of the DB credentials in the .env file) into the source code of the connector and then subsequently into the version control system (as mentioned in the comments of that link)?

Is there a better way to do this?

**Comment by bohdanszymanik** [comment]
Isn't this where credential vaults like hashicorp vault become useful?

**Comment by Jonny-Cornwell-i2** [comment]
@nondeterminickstic yes that would just move the secret being used for the encryption (see `process.env.PASS` in the stackoverflow) into an environment variable not necessarily source code, so you will still need to provide a secret to decrypt the other value and are then back at the same situation.

Ultimately the person deploying the connector server will be the person configuring the environment, this person will be a trusted individual who has access to any secrets required for deploying the connector and can set environment variables accordingly. Only trusted individuals should be able to access the live deployed connector.

As @bohdanszymanik said, you could consider having a vault but again some sort of credentials to access that vault will needed.

**Comment by Anthony-Johnson-i2** [comment]
Hi @nondeterminickstic I am just checking to see if this  issue can be closed out now or if you need more information form development .
Cheers
