### ISSUE TITLE
Loading an image to use as an icon

### ISSUE THREAD

**Issue by bohdanszymanik** [i2group/analyze-connect-node-sdk#22]
It looks to me as though it's not possible to load in an image from a connector and use it to replace an entity icon? Just checking my assumption on that.

**Comment by Anthony-Johnson-i2** [comment]
Hi @bohdanszymanik 

You could get your connector to provide/save the image in an accessible location and add a URL to that as an ImageUrl in a 
 SourceReference it then adds to your entity result which can be used in place of the icon.

[ISourceReference interface](https://i2group.github.io/analyze-connect-node-sdk/api/i2connect.records.isourcereference.html)

However, currently if you use images of type .png it will display well in the record inspector but not very well in the chart . This is a known issue that has been fixed internally but is not yet in released product.

Cheers

**Comment by bohdanszymanik** [comment]
Great - that will work for us. Thanks.
