### ISSUE TITLE
Bulk id search

### ISSUE THREAD

**Issue by bohdanszymanik** [i2group/analyze-connect-node-sdk#23]
Feature request

It would be useful to have a way to search a batch of ids. I can see how we can do this by eg comma separating a string of ids but thought I'd raise it here as it's something that others might have a need for and perhaps could be handled more effectively through the external search UI eg an option to load a file of ids separated by comma/tab/newline etc. 

Not sure where best to put these feature suggestions so let me know if I should move them to a different channel.

**Comment by Anthony-Johnson-i2** [comment]
Hi @bohdanszymanik 

As this is a request for enhancement (RFE) to the UI and the interactions we support via i2 Connect, if you have an active support contract you can raise a support ticket with us.

You can  do that from[ here.](https://i2group.com/support-request)

Cheers

**Comment by bohdanszymanik** [comment]
Great thanks - onto it:)
