### ISSUE TITLE
Add styling to link/entity via the connector

### ISSUE THREAD

**Issue by stvdo** [i2group/analyze-connect-node-sdk#24]
Good afternoon,

Is it somehow possible to add styling via the connector? Based on the field contact I would like to change the color of the line to green (positive) or red (negative).

![image](https://github.com/user-attachments/assets/21f10fb6-a680-4d62-a13f-717b3fd61c5d)

I can make a plugin for that, but that's a step 'too' much in my opinion.

**Comment by Anthony-Johnson-i2** [comment]
Hi @stvdo 

Unfortunately there is no support for visual styling being controlled from a connector.

Cheers

**Comment by stvdo** [comment]
Hi @Anthony-Johnson-i2 

Thank you for you reply. Please could you create a RFE for this, or live formatting this would also solve my challenge:)

**Comment by Anthony-Johnson-i2** [comment]
Hi @stvdo  we have raised 2 RFE's  on your behalf, one for adding visual styling control to the connector and one for making live formatting available in the Web Client.

Cheers

**Comment by Timon-IW** [comment]
Hello,

I wanted to ask if the link strength is also visual styling?
I thought it was possible to change the strength from the connector, could it be that I have an older version in mind?
Like the loopback or something like this.

**Comment by Colvin-Cowie-i2** [comment]
Hello, link strength isn't currently supported in i2 Analyze / i2 Connect or the web client.
ANB Desktop / iBase have link strength.

**Comment by Timon-IW** [comment]
Hi @Colvin-Cowie-i2 ,
I wasn't aware of this, I'm currently working with the ANB Desktop. 
Is it possible to use the connector there to set it?

**Comment by Anthony-Johnson-i2** [comment]
Hi @Timon-IW  as Colvin mentioned above strength isn't currently supported in i2 Analyze / i2 Connect or the web client.

As your connector uses i2 Connect it is does not intrinsically know about link strengths. 

However, if you have a property that you can include in the link records you return that can hold a link strength value that you use to represent Link Strength in your external source then a work around you could use is Live Formatting. 

This is a special form of Conditional formatting that can be given rules based on Analyze record properties and that can be configured to automatically run whenever new Analyze records (like the ones coming from your connector) are added to an ANB desktop chart.

This is documented here:
https://docs.i2group.com/anb/10.1.0/about_live_format.html

I don't have a connector with a property that has strength values in it but you can see from the screen shot below how you might use such a property to alter the displayed link strength.  

![Image](https://github.com/user-attachments/assets/7233dc56-23b7-4fd8-b6b4-707684fcf975)




Please note that this is just a visual representation on the chart so if you were to upload your records retrieved from your connector to the information store you would need a similar Live Formatting rule for those if/when they were charted from the Information store to another chart at a later date.

**Comment by Timon-IW** [comment]
Hello @Anthony-Johnson-i2 ,

Big thank you for the detailed response. For some reason, I didn't saw the "i2 Connect" in the answer from Colvin, sorry.
I will try to do something like what you showed.
