### ISSUE TITLE
Give feedback to user when there are no search results

### ISSUE THREAD

**Issue by stvdo** [i2group/analyze-connect-node-sdk#28]
Good afternoon,

I am trying to give feedback/suggestion to the user of a connector when there are no search results.

1. Run the connector
![image](https://github.com/user-attachments/assets/69c6ac94-936f-4378-b13c-ddad4008dbc1)

2. No results are visible, which is good because there are no results.
![image](https://github.com/user-attachments/assets/c7531597-20c4-4672-8f90-1c3838fad874)

3. Now I add the suggestion in the logs and I throw a Detailed Error. But this is not visible for the user. It would be nice if a message is visible instead of the search results in ANB. 

See below the current code. Hope you have a suggestion to improve this.

![image](https://github.com/user-attachments/assets/4997939b-41f2-44aa-b5cb-5f16cc52a5ab)

A bit like this
![image](https://github.com/user-attachments/assets/10995cb8-c827-4508-84a6-5a5de38cdc0c)

**Comment by Jonny-Cornwell-i2** [comment]
Hi @stvdo,

It looks like you are catching and suppressing the error you have just thrown in your connector code as you are throwing the error within a try catch that subsequently "catches" and calls `console.error`. This ultimately means the code which responds to the `DetailedError` being thrown will never execute.
![image](https://github.com/user-attachments/assets/f24df731-599e-41e9-b0ba-8f19ca674fee)

**Comment by stvdo** [comment]
Thanks a lot for the explanation and quick help @Jonny-Cornwell-i2
