### ISSUE TITLE
i2Connect DateTime from MS SQL Server

### ISSUE THREAD

**Issue by jcgleroux** [i2group/analyze-connect-node-sdk#3]
Use of toJSDate and/or toISOString is not giving the correct result in javascript/typescript.
I have tried different methods and different selects from SQL Server but does not get the correct result.
Are there any suggestions on how to use the methods to get the correct result?

**Comment by Anthony-Johnson-i2** [comment]
Hi, 
Our SDK does  give some information here:

[i2 Connect Data Namespace](https://i2group.github.io/analyze-connect-node-sdk/api/i2connect.data.html)

 Have you had a look at the w3schools  reference here :

[JavaScript Date Formats](https://www.w3schools.com/js/js_date_formats.asp)

[JavaScript Date Objects](https://www.w3schools.com/js/js_dates.asp)

 They might help you figure it out.
 
Cheers
