### ISSUE TITLE
Get the entity and property by ID for Visual query.

### ISSUE THREAD

**Issue by Timon-IW** [i2group/analyze-connect-node-sdk#30]
Greetings,

I am trying to make a connector with a visual query.
The problem that I am facing now is that I need to get the entity type and property type for my request to the database.
But the visual query object only has the IDs from the schema, so I would need to make multiple iterations over the schema to get the information I want. 
for example, I have a query about a person (ET1) and want to filter by the birth year (PT5). The Links aside for now.
I would have to loop over the schema to find the object (entity) with the id ET1, and then do another loop to get the property with the id PT5.
It would be better if I could get it without the looping, so like schema.entityTypes.[ET1] for the entity and for the property schema.entityTypes.[ET1].[PT5] or schema.entityTypes.person.[PT5].
The identifier for the object path is already the name, so I'm pretty sure this isn't possible, but maybe something alike.
If I missed something in the documentation, or it's not clear what I mean, please let me know.

**Comment by Mark-Falconbridge-i2** [comment]
There's nothing built in for that but you could create your own map from the schema along these lines that you can access via id to get entity type and then the property type via id again:

```
const entitiesMap = new Map(
  Object.values(schema.entityTypes).map((entityType) => [
    entityType.id,
    {
      ...entityType,
      propertyTypesMap: new Map(
        Object.values(entityType.propertyTypes).map((propertyType) => [propertyType.id, propertyType])
      ),
    },
  ])
);
```

**Comment by Anthony-Johnson-i2** [comment]
Hi @Timon-IW  did what @Mark-Falconbridge-i2  suggested above enable you to resolve your issue?

**Comment by Anthony-Johnson-i2** [comment]
Closing as no response received after information given, or when re queried, so presuming that this is no longer an issue.
