### ISSUE TITLE
Better VisualQueryCondition handling

### ISSUE THREAD

**Issue by Timon-IW** [i2group/analyze-connect-node-sdk#31]
Greetings,

I was wondering if there is a better way of handling the VisualQueryCondition array.
Currently, I'm doing this:
```
    var cond: spi.VisualQueryNumericCondition | spi.VisualQueryBooleanCondition | spi.VisualQueryStringCondition 
       | spi.VisualQueryDateAndTimeCondition = entity.conditions.[i];
    year = cond.values?.[0].toString();
```
Because if I don't reassign it, it tells me there is no values property on the object.
And I need to add a new possible condition from now and then.
I tried to put an 'if' in front to check the valueType, like with the entities, if I want a property value, I need to check the entity type so that I can access it.

Best regards,
Timon Brunnert

**Comment by Jonny-Cornwell-i2** [comment]
Hi @Timon-IW,

So in this instance we'll need to write the code which handles the various different types of condition values. These values should be treated as immutable . One approach is to do the following:

```ts
  if (vqItem.conditions) {
    for (const element of vqItem.conditions) {
      switch (element.valueType) {
        case 'STRING': {
          const stringCondition = element as spi.VisualQueryStringCondition;
          console.log(stringCondition.values); // stringCondition.values is an array of strings
          break;
        }

        case 'NUMBER': {
          const numberCondition = element as spi.VisualQueryNumericCondition;
          console.log(numberCondition.values); // numberCondition.values is an array of numbers
          break;
        }

        case 'BOOLEAN'

        ...
      }
    }
  }
```

It is worth remembering that in VQ conditions there can be multiple conditions which related to the same property type, along with having multiple values per condition in the case of strings. Any queries that are constructed should bear this in mind and you shouldn't really ever be accessing values at positions e.g. by accessing index 0 (`values[0]`)

**Comment by Timon-IW** [comment]
Hello,

I see that you are doing the same thing with the reassignment, just divided by the type.
And yes, I am aware that this is not how it should be done later, but it's sufficient for my testing. 

Still thank you for your response and I now know that I would have to do it that way.

Hoping you have a wonderful week.
