### ISSUE TITLE
Question about authentication token expiration

### ISSUE THREAD

**Issue by stvdo** [i2group/analyze-connect-node-sdk#32]
Good morning,

I followed the instruction for the authentication, https://i2group.github.io/analyze-connect-node-sdk/guide/miscellaneous/auth-config.html?q=createAuthenticator.

This works perfectly, except for resetting the authToken when it's expired (e.g. after 15 minutes). I can't find how I can trigger the authentication to request again for the username and password.

I tried it manual with a service, but it doesn't show the username/password popup again.

```
addService(
  {
    id: 'dummyService',
    name: 'A service to simulate the expiration of the token',
    description: 'A service requiring the user to authenticate themselves',
    authenticator: usernameAndPasswordAuthenticator,
  },
  ({ authToken }) => {
    // Check the authentication token is valid
    if (authToken != '') {
      // Continue with service acquire...
      console.log('token', authToken);
      // remove token to simulate a authentication error from CMS
      authToken = '';
      console.log('token', authToken);
    } else {
      throw new AuthenticationRequiredError({ title: 'The authentication token is no longer valid' });
    }
  }
);
```

**Comment by stvdo** [comment]
In the mean time I found out that throwing a AuthenticationRequiredError will trigger the login form. But maybe there is a better way:)

```
addService(
  {
    id: 'dummyService',
    name: 'A service to simulate the expiration of the token',
    description: 'A service to simulate the expiration of the token',
    authenticator: usernameAndPasswordAuthenticator,
  },
  ({ authToken }) => {
    // Check the authentication token is valid
    if (authToken != '') {
      // Continue with service acquire...
      console.log('token', authToken);
      // remove token to simulate a authentication error from CMS
      //authToken = '';
      console.log('token', authToken);
      throw new AuthenticationRequiredError({ title: 'The authentication token is now removed' });
    } else {
      throw new AuthenticationRequiredError({ title: 'The authentication token is no longer valid' });
    }
  }
);
```

**Comment by Mark-Falconbridge-i2** [comment]
I think you've hit the nail on the head, the documentation you linked to states that:

"To mark a service as requiring authentication, you specify the authenticator as a property of the service configuration. The service is then passed the token that was returned by the authenticator (authentication-token in the example). If required, the service can verify that the token is still valid, and throw an AuthenticationRequiredError if it's not."

**Comment by stvdo** [comment]
@Mark-Falconbridge-i2 thanks a lot Mark!
