### ISSUE TITLE
User name AND token in service

### ISSUE THREAD

**Issue by stvdo** [i2group/analyze-connect-node-sdk#33]
Good morning,

In the example only the token is passed in the service (https://i2group.github.io/analyze-connect-node-sdk/guide/miscellaneous/auth-config.html).

Beside the token I have to pass the username to the 3th party API. How can I extract the username from the Authenticator?

```
addService(
  {
    id: 'dummyService',
    name: 'A service to simulate the expiration of the token',
    description: 'A service to simulate the expiration of the token',
    authenticator: usernameAndPasswordAuthenticator,
  },
  ({ authToken }) => {
    console.log('token', authToken);
    throw new AuthenticationRequiredError({ title: 'The authentication token is now removed' });
  }
);
```

**Comment by Anthony-Johnson-i2** [comment]
Hi @stvdo  Steven

Can your connector get the user information needed from this if you have `send-sensitive-headers`  set?

[services.IRequestInformation.user property](https://i2group.github.io/analyze-connect-node-sdk/api/i2connect.services.irequestinformation.user.html?q=user%20name)

**Comment by stvdo** [comment]
@Anthony-Johnson-i2 

I think there are 2 different users. With the function you mentioned it's possible to pass over the i2 Analyze login to the connector.

But I would like to retrieve the user from the services.IAuthenticator.

![image](https://github.com/user-attachments/assets/7a19fe9b-99a9-4ee8-a8a9-b60a7186b1c6)

**Comment by Mark-Falconbridge-i2** [comment]
I'm afraid it's not possible to get the information the user provided from the Authenticator.

**Comment by stvdo** [comment]
@Mark-Falconbridge-i2 thank you for your response. Please could you create a RFE for this?

**Comment by Mark-Falconbridge-i2** [comment]
A workaround might be to encode the username in the token that you return from the Authenticator. Since the format is known to you in the Authenticator and the service you could deserialize the token retrieving both parts, the actual token and the username.

**Comment by Anthony-Johnson-i2** [comment]
Hi @stvdo I have created an  RFE for this .
