### ISSUE TITLE
Prefill form field with field from the seed

### ISSUE THREAD

**Issue by stvdo** [i2group/analyze-connect-node-sdk#34]
Good morning,

I created a service with a form OR seed as input. If I use the seed I would like to prefill the form. Is this possible?

![image](https://github.com/user-attachments/assets/cae36814-9ac8-431f-910b-554869cf8dd3)

Or can you hide the form when you have a seed as input?

**Comment by Mark-Falconbridge-i2** [comment]
Right now, that's not possible. Your best bet is to create two services, one seeded and one not and in the seeded case, not show the corresponding part of the form.

You should be able to share a lot of the logic between the two services but you are still stuck with two services.

**Comment by stvdo** [comment]
@Mark-Falconbridge-i2 thank you for your response. Please could you create a RFE for this?

**Comment by Anthony-Johnson-i2** [comment]
Hi @stvdo Steven I have created an RFE for this.
