### ISSUE TITLE
[Enhancement Request] To have a expand button when using i2 Connect on ANBP

### ISSUE THREAD

**Issue by agui-va** [i2group/analyze-connect-node-sdk#35]
There's a request from a customer for a expand button on the ribbon bar when using i2 Connect.
Details as follows:
Adding of a expand button on the ribbon bar that have a seeded non-parametrized query bound to it so that the button will execute the query rather than locating and running the query.

Also since it's quite gray if this enhancement is to be on i2 Connect or ANBP, I'll also send in the enhancement request as a ticket to the support desk.

**Comment by Mark-Falconbridge-i2** [comment]
It sounds like the request is for an accelerator in the ANBP ribbon to run a specific query. i2 Connect can't add buttons into the ANBP ribbon.

**Comment by Anthony-Johnson-i2** [comment]
Thanks for the response @Mark-Falconbridge-i2 ,  it sounds like Alex @agui-va  has done the right thing by asking for an RFE via the official support route.

I just checked Alex, and we have the RFE in our system so I will close out this issue now.

Thank you.
