### ISSUE TITLE
Change schema path

### ISSUE THREAD

**Issue by Timon-IW** [i2group/analyze-connect-node-sdk#5]
Hello There,

is there any option to change the Path from where the TS Schema is generated.
I don't want to copy the schema every time I edit it. 
I want a key place where the node-sdk takes it from automatically.

**Comment by Jonny-Cornwell-i2** [comment]
Hi Timon,

Currently there is no way to do this but I am keen to gather a bit more information before potentially escalating a feature request. What type of [schema(s) are you using (`connector`, `gateway` and/or `infoStore`)](https://i2group.github.io/analyze-connect-node-sdk/api/i2connect.connectors.ischemas.html)?

I would note that if you are using a `connector` schema we require both the generated TS file and the XML schema as runtime dependencies so there will always need to be a copy of the schema in the connector code.

Jonny

**Comment by Timon-IW** [comment]
Thank you for the reply, 

I was hoping to avoid having the schema in the connector code. We are using and the infoStore and a connector. 
The connector's components are designed to align with the information store's content when inserted into the chart. Therefore, the schema is specifically designed for the infoStore, and the connector should be capable of utilizing that schema. We hoped that we would not have to copy the schema over every time we were modifying it.

**Comment by Jonny-Cornwell-i2** [comment]
Sorry for the delayed response, thanks for the concise reply. I will raise something internally to investigate what we could potentially do to resolve this issue. My immediate thoughts are potentially using environment variables to specify a path for gateway and infoStore schemas which we watch during dev.

**Comment by Anthony-Johnson-i2** [comment]
Did you need this to be held open any more @Jonny-Cornwell-i2 ?

**Comment by Anthony-Johnson-i2** [comment]
Closing as an internal task has been raised to look into improving this for a future release.
