### ISSUE TITLE
Increasing the 10k record query cap

### ISSUE THREAD

**Issue by RaymondVA** [i2group/analyze-connect-node-sdk#6]
Hi i2Group,

If there are more than 10k records returned by a service, is there a way to increase the cap limit so that i2Analze can return >10k records?

Kind regards,
Raymond.

**Comment by Colvin-Cowie-i2** [comment]
Hello, please see https://github.com/i2group/analyze-connect/issues/12#issuecomment-1057973456 for the limit enforced by the server

**Comment by Colvin-Cowie-i2** [comment]
No problem
