### ISSUE TITLE
setProperties on the seed

### ISSUE THREAD

**Issue by sdorresteijn88** [i2group/analyze-connect-node-sdk#7]
Good morning,

I created a car-registration connector. It happens that the seed entity has only a license plate number and that other information like the color is available in the connected source. How can I apply the color e.g. to the seeded entity?

seed.setProperties gives this error: Property 'setProperties' does not exist on type 'ISeedEntityRecord'.

**Comment by Anthony-Johnson-i2** [comment]
Hi @sdorresteijn88 

We have been discussing this internally and currently it is not possible to edit existing items in i2 Notebook you can do this in Analyst's Notebook premium though.

I think @Ralph-Klaassen-i2  is reaching out to you separately on this too.

Cheers

**Comment by sdorresteijn88** [comment]
Hi Anthony,

Ralph reached me indeed, this is now solved. Thanks a lot!
